apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: onskfov9h-nodejs-gitops
  description: This is GitOps manifest for onskfov9h-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=onskfov9h-nodejs
    backstage.io/kubernetes-id: onskfov9h-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: onskfov9h-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:onskfov9h-nodejs
