apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: onskfov9h-nodejs
  janus-idp.io/tekton: onskfov9h-nodejs
  backstage.io/kubernetes-id: onskfov9h-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: onskfov9h-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
